// flow-typed signature: d5911bc19efd027bb508e53be380e2f3
// flow-typed version: <<STUB>>/normalize.css_v8.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
